---
- hosts: all
  become: yes
  
  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: install Docker
    yum:
      name: docker
      state: present
      update_cache: true

  - name: start Docker
    service:
      name: docker
      state: started
  
  - name: disabling Swap on all nodes
    shell: swapoff -a

  - name: commenting Swap entries in /etc/fstab
    replace:
      path: /etc/fstab
      regexp: '(.*swap*)'
      replace: '#\1'

  - name: disable SELinux
    command: setenforce 0
    ignore_errors: true
    changed_when: false

  - name: disable SELinux on reboot
    selinux:
      state: disabled

  - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

  - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

  - name: add Kubernetes' YUM repository
    yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

  - name: install kubelet
    yum:
      name: kubelet
      state: present
      update_cache: true

  - name: install kubeadm
    yum:
      name: kubeadm
      state: present

  - name: start kubelet
    service:
      name: kubelet
      enabled: yes
      state: started

- hosts: master
  become: yes

  tasks:
  - name: install kubectl
    yum:
     name: kubectl
     state: present

  - name: add port to firewalld (master)
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - 6443/tcp
      - 2379-2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
      - 10255/tcp
  
  - name: reload service firewalld (master)
    systemd:
      name: firewalld
      state: reloaded

- hosts: workers
  become: yes

  tasks:
  - name: add port to firewalld (workers)
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - 10251/tcp
      - 10255/tcp
  
  - name: reload service firewalld (workers)
    systemd:
      name: firewalld
      state: reloaded
